### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by kaozente** [kaozente/SlackerNews#19]

**Comment by olegsfinest** [comment]
/home/slacker/.config/letsencrypt/live/slackernews.de/fullchain.pem.
   Your cert will expire on 2018-03-13

**Comment by olegsfinest** [comment]
www. noch weiterleiten. geht glaube ich im uberspace nicht so easy

**Comment by olegsfinest** [comment]
auf neuem server auch wieder einrichen
