### ISSUE TITLE
Kategorien url mit slug statt id

### ISSUE THREAD

**Issue by olegsfinest** [kaozente/SlackerNews#20]
für eine schönere url der kategorien, deren slug als id nutzen und nicht die integer id.

Erstmal krass unwichtig aber für später

**Comment by olegsfinest** [comment]
slugs are introduced; should find their way into the url

**Comment by kaozente** [comment]
friendly id gem?

**Comment by olegsfinest** [comment]
glaube das war das standard gem dafür (Y)
