### ISSUE TITLE
Kombination Inhalt / Sortierung

### ISSUE THREAD

**Issue by kaozente** [kaozente/SlackerNews#38]
* routing
* Controller
* sauber abmodeln damit das nicht grausam langsam wird ab 100 posts

**Comment by kaozente** [comment]
https://www.justinweiss.com/articles/search-and-filter-rails-models-without-bloating-your-controller/

**Comment by olegsfinest** [comment]
Jo scopes sind bombe zum suchen, hab ich im optimus auch benutzt. das ändert auch die sql anfrage im vorhinein schon richtig ab.

**Comment by kaozente** [comment]
jetzt per scope + before_action, performance muessen wir mal im auge behalten
