### ISSUE TITLE
Category Managment

### ISSUE THREAD

**Issue by kaozente** [kaozente/SlackerNews#5]

**Comment by olegsfinest** [comment]
We need to decide upon a process, how categories can be generated:

**Proposal:** Anybody can propose a new category, but admins have to approve it

**Comment by olegsfinest** [comment]
<img width="1136" alt="bildschirmfoto 2017-10-16 um 16 53 01" src="https://user-images.githubusercontent.com/4113982/31618543-8742486a-b292-11e7-9d9e-6ad3752aa22d.png">
(zu fauls das abzutippen)
