### ISSUE TITLE
Heatness-Algorithmus

### ISSUE THREAD

**Issue by olegsfinest** [kaozente/SlackerNews#8]
Funktion auf den Votes mit Datum etc eeinberechnet, dass es neben Top/New auch Hot gibt

Verhindern, dass das jedes mal neu berechnet wird

**Comment by olegsfinest** [comment]
generel für den start:

* newest
* Top (und das dann für verschiedene zeiten)
  * 1 tag
  * 1 woche
  * [...]

Darauf aufbauen dann so n geilen adaptiven heatnes shit

**Comment by kaozente** [comment]
Basic Heat Algo ist erstmal drin!
